# general settings
name: transweather_uncertainty_batch_32
model_type: transweather_uncertainty_5_types
scale: 1
num_gpu: 1 
manual_seed: 0

datasets:
  train:
    name: PromptTrainDataset
    type: PromptTrainDataset
    phase: train
    data_file_dir: /dev/shm/AirNet-Data/data_dir/  
    denoise_dir: /dev/shm/AirNet-Data/data/Train/Denoise/ 
    derain_dir: /dev/shm/AirNet-Data/data/Train/Derain/  
    dehaze_dir: /dev/shm/AirNet-Data/data/Train/Dehaze/ 
    gopro_dir: /dev/shm/AirNet-Data/data/Train/GoPro/  
    lol_dir: /dev/shm/AirNet-Data/data/Train/LOL/  
  
    de_type: ['denoise_15', 'denoise_25', 'denoise_50', 'derain', 'dehaze','gopro','lol']  # 使用
    patch_size: 256

    num_worker_per_gpu: 8
    batch_size_per_gpu: 32
    dataset_enlarge_ratio: 1
    prefetch_mode: ~

  val:
    name: denoise_25
    type: PairedImageDataset_for_transweather
    dataroot_gt: /dev/shm/AirNet-Data/test/denoise/bsd68
    dataroot_lq: /dev/shm/AirNet-Data/test/denoise/noisy25
    gt_size: 256
    io_backend:
      type: disk


# network structures
network_g:
  type: Transweather
  if_uncertainty: true



# path
path:
  pretrain_network_g: ~
  param_key_g: ~
  strict_load_g: false
  resume_state: ~
# training settings
train:
  ema_decay: 0.999
  optim_g:
    type: Adam
    lr: !!float 1e-4
    weight_decay: 0
    betas: [0.9, 0.99]

  scheduler:
    type: CosineAnnealingRestartLR  
    periods: [250000,250000,250000,250000,250000,250000,250000,250000,250000,250000]
    restart_weights: [1,1,1,1,1,1,1,1,1,1]
    eta_min: !!float 1e-7

  total_iter: 2500000
  warmup_iter: -1  # no warm up

  # losses
  pixel_opt:
    type: airnet_uncertainty_loss_5_types
    # loss_weight: 1.0
    # reduction: mean


# logging settings
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 1e4
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500

val:
  val_freq: 10000
  save_img: false

  metrics:
    psnr: # metric name, can be arbitrary
      type: calculate_psnr
      crop_border: 0
      test_y_channel: false
